In [3]:
import torch
from torch import nn

In [2]:
model = torch.load("datasets/split/block_splits_by_image_all.pth")

In [3]:
model.keys()

dict_keys(['splits'])

In [4]:
type(model['splits'])

list

In [5]:
len(model['splits'])

6

In [7]:
model0 = model['splits'][0]

In [8]:
type(model0)

dict

In [10]:
model1 = model['splits'][0]

In [11]:
model1.keys()

dict_keys(['train', 'val', 'test'])

---

In [14]:
model_single = torch.load("datasets/split/block_splits_by_image_single.pth")

In [15]:
len(model_single['splits'])

1

In [17]:
model_sin_splits = model_single['splits'][0]

In [18]:
model_sin_splits.keys()

dict_keys(['train', 'val', 'test'])

In [21]:
len(model_sin_splits['train'])

669

In [22]:
len(model_sin_splits['val'])

167

In [23]:
len(model_sin_splits['test'])

164

In [24]:
test = model_sin_splits['test']

In [27]:
test[0]

1

---

# datasets/eeg/

In [6]:
# eeg1470 = torch.load("datasets/eeg/eeg_14_70_std.pth")
eeg0595 = torch.load("dreamdiffusion/datasets/eeg_5_95_std.pth")

In [9]:
eeg0595.keys()

dict_keys(['dataset', 'labels', 'images'])

In [10]:
dataset, labels, images = eeg0595['dataset'], eeg0595['labels'], eeg0595['images']

In [11]:
len(dataset)

11965

In [12]:
len(labels)

40

In [13]:
len(images)

1996

In [31]:
dataset[0]

{'eeg': tensor([[-0.0098,  0.0195,  0.0620,  ...,  0.0638,  0.0120, -0.0118],
         [-0.0045,  0.1303,  0.2673,  ...,  0.0894,  0.0342, -0.0082],
         [ 0.0215, -0.2017, -0.4305,  ..., -0.2022, -0.0940,  0.0188],
         ...,
         [ 0.0160,  0.0707,  0.1005,  ...,  0.2066,  0.1156,  0.0036],
         [-0.0046, -0.0084, -0.0119,  ...,  0.0007, -0.0026, -0.0053],
         [ 0.0040,  0.0419,  0.0665,  ...,  0.0765,  0.0309, -0.0063]]),
 'image': 0,
 'label': 10,
 'subject': 4}

In [32]:
dataset[0]['label']

10

In [9]:
import math
print(int(2 * math.log2(256)))
print(int(2 * math.log2(128)))
print(int(2 * math.log2(64)))
print(int(2 * math.log2(32)))

16
14
12
10


In [15]:
dataset[0]['image']

0

In [16]:
images[1]

'n03452741_16744'

In [17]:
labels[30]

'n03452741'

In [18]:
images[:10]

['n02951358_31190',
 'n03452741_16744',
 'n04069434_10318',
 'n02951358_34807',
 'n03452741_5499',
 'n03376595_247',
 'n02906734_14010',
 'n03452741_2982',
 'n02607072_5873',
 'n02510455_96034']

In [20]:
# model3['images'][0]

In [236]:
model3['dataset'][1995]

{'eeg': tensor([[-0.0299, -0.0996, -0.1700,  ..., -0.2839, -0.1543, -0.0182],
         [-0.0239, -0.0608, -0.0974,  ..., -0.2596, -0.1397, -0.0193],
         [ 0.0169, -0.0083, -0.0199,  ..., -0.1203, -0.0589,  0.0250],
         ...,
         [ 0.0026,  0.0682,  0.1460,  ..., -0.3128, -0.1583, -0.0072],
         [-0.0024, -0.0029, -0.0025,  ..., -0.0274, -0.0152, -0.0029],
         [-0.0066, -0.0389, -0.0570,  ..., -0.4324, -0.2266, -0.0158]]),
 'image': 1995,
 'label': 13,
 'subject': 4}

In [231]:
model3['labels'][:20]

['n02389026',
 'n03888257',
 'n03584829',
 'n02607072',
 'n03297495',
 'n03063599',
 'n03792782',
 'n04086273',
 'n02510455',
 'n11939491',
 'n02951358',
 'n02281787',
 'n02106662',
 'n04120489',
 'n03590841',
 'n02992529',
 'n03445777',
 'n03180011',
 'n02906734',
 'n07873807']

In [233]:
model3['images'][:20]

['n02951358_31190',
 'n03452741_16744',
 'n04069434_10318',
 'n02951358_34807',
 'n03452741_5499',
 'n03376595_247',
 'n02906734_14010',
 'n03452741_2982',
 'n02607072_5873',
 'n02510455_96034',
 'n02281787_4182',
 'n02906734_508',
 'n03272010_4472',
 'n04044716_691',
 'n03272562_1177',
 'n03773504_14125',
 'n02607072_3895',
 'n03272010_6902',
 'n03709823_451',
 'n02389026_2743']

In [229]:
model3['dataset'][-1]

{'eeg': tensor([[ 0.0708, -0.1510, -0.4029,  ..., -0.6999, -0.3084,  0.0657],
         [ 0.2275, -0.3112, -0.9725,  ..., -1.2034, -0.4301,  0.2263],
         [-0.0719,  0.0073,  0.1354,  ...,  0.1094, -0.0090, -0.0722],
         ...,
         [-0.1027,  0.5589,  1.2396,  ...,  1.0714,  0.4695, -0.1056],
         [-0.0073,  0.0235,  0.0556,  ...,  0.0529,  0.0222, -0.0074],
         [-0.0838,  0.4055,  0.9156,  ...,  0.9054,  0.4006, -0.0851]]),
 'image': 1995,
 'label': 13,
 'subject': 5}

In [161]:
model3['labels'][0]

'n02389026'

In [128]:
labels = sorted(model3['labels'])

In [129]:
labels[0]

'n02106662'

In [141]:
labels[model3['dataset'][0]['label']]

'n02951358'

In [124]:
model3['labels'][0]

'n02389026'

In [180]:
data_label_list = []

for i in range(len(model3['dataset'])):
    data_label_list.append(model3['dataset'][i]['label'])

In [200]:
for i in range(10):
    print(model3['labels'][data_label_list[i]])

n02951358
n03452741
n04069434
n02951358
n03452741
n03376595
n02906734
n03452741
n02607072
n02510455


In [208]:
data_label_list_str = []
for i in range(len(model3['labels'])):
    data_label_list_str.append(model3['labels'][i])

In [210]:
data_label_list_str[:10]

['n02389026',
 'n03888257',
 'n03584829',
 'n02607072',
 'n03297495',
 'n03063599',
 'n03792782',
 'n04086273',
 'n02510455',
 'n11939491']

In [219]:
model3['images'][0]

'n02951358_31190'

In [220]:
data_image_dict = {}
for i in model3['images']:
    for j in data_label_list_str:
        if i[:9] == j:
            

In [222]:
data_image_list[:10]

['n02951358_31190',
 'n03452741_16744',
 'n04069434_10318',
 'n02951358_34807',
 'n03452741_5499',
 'n03376595_247',
 'n02906734_14010',
 'n03452741_2982',
 'n02607072_5873',
 'n02510455_96034']

In [125]:
images = sorted(model3['images'])

In [126]:
images[0]

'n02106662_10232'

In [154]:
model3['images'][:10]

['n02951358_31190',
 'n03452741_16744',
 'n04069434_10318',
 'n02951358_34807',
 'n03452741_5499',
 'n03376595_247',
 'n02906734_14010',
 'n03452741_2982',
 'n02607072_5873',
 'n02510455_96034']

In [35]:
import torch
from torch import nn
import pickle

In [29]:
import numpy as np
import pickle

In [30]:
m = np.load('dataset/eeg_imagenet40_cvpr_2017_raw/test/n02106662_16778_1.npy', allow_pickle=True)

FileNotFoundError: [Errno 2] No such file or directory: 'dataset/eeg_imagenet40_cvpr_2017_raw/test/n02106662_16778_1.npy'

In [26]:
print(m), print(len(m))

[array([[[117, 104,  85],
         [120, 107,  88],
         [125, 112,  93],
         ...,
         [ 74,  73,  53],
         [ 72,  71,  51],
         [ 72,  71,  51]],

        [[117, 104,  85],
         [120, 107,  88],
         [125, 112,  93],
         ...,
         [ 91,  90,  70],
         [ 81,  80,  60],
         [ 75,  74,  54]],

        [[118, 105,  86],
         [121, 108,  89],
         [125, 112,  93],
         ...,
         [110, 109,  91],
         [ 99,  98,  80],
         [ 92,  91,  73]],

        ...,

        [[ 59,  41,  27],
         [ 60,  43,  27],
         [ 59,  42,  24],
         ...,
         [129, 115,  80],
         [126, 112,  77],
         [123, 109,  74]],

        [[ 72,  55,  39],
         [ 69,  52,  34],
         [ 62,  45,  25],
         ...,
         [124, 110,  75],
         [121, 107,  72],
         [118, 104,  69]],

        [[ 98,  81,  63],
         [ 91,  74,  54],
         [ 78,  62,  39],
         ...,
         [112,  98,  63],
        

(None, None)

In [21]:
print(m[0])

[[[117 104  85]
  [120 107  88]
  [125 112  93]
  ...
  [ 74  73  53]
  [ 72  71  51]
  [ 72  71  51]]

 [[117 104  85]
  [120 107  88]
  [125 112  93]
  ...
  [ 91  90  70]
  [ 81  80  60]
  [ 75  74  54]]

 [[118 105  86]
  [121 108  89]
  [125 112  93]
  ...
  [110 109  91]
  [ 99  98  80]
  [ 92  91  73]]

 ...

 [[ 59  41  27]
  [ 60  43  27]
  [ 59  42  24]
  ...
  [129 115  80]
  [126 112  77]
  [123 109  74]]

 [[ 72  55  39]
  [ 69  52  34]
  [ 62  45  25]
  ...
  [124 110  75]
  [121 107  72]
  [118 104  69]]

 [[ 98  81  63]
  [ 91  74  54]
  [ 78  62  39]
  ...
  [112  98  63]
  [109  95  60]
  [105  91  56]]]


In [22]:
print(m[1])

[[ -10.  -28.   30. ...  514.  863.  134.]
 [ 574.  430.   -7. ...  343.  426.  482.]
 [ 497. -542.  828. ...  686.  958.  106.]
 ...
 [ 208.  267.  136. ...  -95.    3. -159.]
 [-188. -149. -133. ... -268.  410.  354.]
 [ 443.  377.  259. ... 2066. 2178. 2982.]]


In [23]:
print(m[2])

12


In [27]:
print(m[3])

n02106662_16778


In [28]:
print(m[4])

1
